### ISSUE TITLE
ValueError: Namespace Gst not available

### ISSUE THREAD

**Issue by gaganyadav80** [SeaDve/Kooha#107]
When I run Kooha on OpenSuSE Tumbleweed I get the following error.
[Installed from OBS](https://build.opensuse.org/package/show/home:Dead_Mozay:GNOME:Apps/kooha)

Can you help me with what is the problem here?

```bash
$ kooha
Traceback (most recent call last):
  File "/usr/bin/kooha", line 44, in <module>
    from kooha import main
  File "/usr/share/kooha/kooha/main.py", line 21, in <module>
    gi.require_version('Gst', '1.0')
  File "/usr/lib64/python3.8/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gst not available
```

**Comment by SeaDve** [comment]
you need to have gstreamer installed in your system

**Comment by gaganyadav80** [comment]
Thanks for your reply and sorry to bug you again.
I solved the above error by installing `gstreamer-devel` as `gstreamer` was already installed.

But now I get something else and can't seem to figure it out.
```bash
$ kooha
Traceback (most recent call last):
  File "/usr/bin/kooha", line 44, in <module>
    from kooha import main
  File "/usr/share/kooha/kooha/main.py", line 26, in <module>
    from kooha.window import KoohaWindow
  File "/usr/share/kooha/kooha/window.py", line 30, in <module>
    @Gtk.Template(resource_path='/io/github/seadve/Kooha/ui/window.ui')
  File "/usr/lib64/python3.8/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'
```

**Comment by SeaDve** [comment]
No problem, that is weirder, I'm not sure where that is coming from.

If you use flatpak, I do recommend using it since you don't have to worry with the dependencies

**Comment by gaganyadav80** [comment]
Alright! Thanks for your time.
