### ISSUE TITLE
Cannot 'select area' on gnome 41 + wayland

### ISSUE THREAD

**Issue by tim-hm** [SeaDve/Kooha#109]
## description of issue

When I try and select an area of the screen to record I'm getting the following error message on gnome 41 + wayland:

```
$ kooha
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/window.py", line 60, in on_start_record_button_clicked
    self.video_recorder.set_selection_mode()
  File "/usr/share/kooha/kooha/recorders.py", line 194, in set_selection_mode
    self.coordinates = self.gnome_selectarea.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: SelectArea is not allowed (9)
```

## expected behaviour

I should get a selection cursor to select an area of the screen and then it should allow me to record that area of the screen.

## system
```
$neofetch --stdout
OS: Arch Linux x86_64 
Host: Z390 AORUS PRO WIFI 
Kernel: 5.14.6-zen1-1-zen 
Uptime: 33 mins 
Packages: 1160 (pacman), 4 (flatpak) 
Shell: fish 3.3.1 
Resolution: 3840x2160 
DE: GNOME 41.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: tmux 
CPU: Intel i9-9900K (16) @ 5.000GHz 
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590 
Memory: 14980MiB / 64246MiB 
```

**Comment by SeaDve** [comment]
gnome 41 removed other appllications access to certain dbus interface which includes SelectArea, this is fixed though in main branch as it doesnt depend on that

**Comment by tim-hm** [comment]
Great I'll try compiling from source

**Comment by SeaDve** [comment]
I'll close this since it is fixed on main, and gonna do a release today, thanks!
