### ISSUE TITLE
Test failure during Arch Linux build

### ISSUE THREAD

**Issue by orhun** [SeaDve/Kooha#197]
**Describe the bug**

```
     Running unittests src/main.rs (src/debug/deps/kooha-19cf5268d23cd292)
thread 'element_properties::tests::element_properties' panicked at 'GStreamer has not been initialized. Call `gst::init` first.', /build/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.8/src/structure.rs:80:9
stack backtrace:
thread 'profile::tests::incompatibles' panicked at 'GStreamer has not been initialized. Call `gst::init` first.', /build/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.8/src/structure.rs:80:9

(kooha-19cf5268d23cd292:10622): GLib-GIO-ERROR **: 16:42:56.486: Settings schema 'io.github.seadve.Kooha' is not installed
error: test failed, to rerun pass '--bin kooha'

Caused by:
  process didn't exit successfully: `/build/kooha/src/build/src/debug/deps/kooha-19cf5268d23cd292 --nocapture` (signal: 5, SIGTRAP: trace/breakpoint trap)
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

5/5 cargo-clippy     OK             139.35s

Summary of Failures:

4/5 cargo-test       FAIL            90.58s   exit status 101

Ok:                 4
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0

Full log written to /build/kooha/src/build/meson-logs/testlog.txt
```

**To Reproduce**
1. Fetch PKGBUILD from https://github.com/archlinux/svntogit-community/blob/packages/kooha/trunk/PKGBUILD
2. Update version to `2.2.2`
3. Build via `extra-x86_64-build`

**Expected behavior**
Successful build.

**Screenshots**
\-

**Additional context**

<details>
<summary>meson-logs/testlog.txt</summary>

```
Log of Meson test suite run on 2022-10-09T16:49:19.037721

Inherited environment: DISPLAY=:99 XAUTHORITY=/tmp/xvfb-run.ZdFft7/Xauthority.JakGk3 SHELL=/bin/bash BUILDTOOL=devtools SUDO_GID=0 PYTHONHASHSEED=0 TEXTDOMAINDIR=/usr/share/locale SUDO_COMMAND='/bin/bash -c bash -c cd\ /startdir;\ makepkg\ "$@" -bash --syncdeps --noconfirm --log --holdver --skipinteg --install' SUDO_USER=root PWD=/build/kooha/src SOURCE_DATE_EPOCH=1665333970 LOGNAME=builduser CXXFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -flto=auto' COMMAND_MODE=legacy LDFLAGS='-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto' HOME=/build LANG=C.UTF-8 RUSTUP_TOOLCHAIN=stable MAKEFLAGS=-j65 TERM=unknown USER=builduser SHLVL=2 CHOST=x86_64-pc-linux-gnu PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl CFLAGS='-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto=auto' SUDO_UID=0 MAIL=/var/mail/builduser BUILDTOOLVER=20220621-1-any OLDPWD=/build/kooha/src TEXTDOMAIN=pacman-scripts _=/usr/bin/meson

==================================== 1/5 =====================================
test:         validate-desktop
start time:   16:49:19
duration:     0.02s
result:       exit status 0
command:      MALLOC_PERTURB_=253 /usr/bin/desktop-file-validate /build/kooha/src/build/data/io.github.seadve.Kooha.desktop
----------------------------------- stdout -----------------------------------
/build/kooha/src/build/data/io.github.seadve.Kooha.desktop: hint: value item "Recorder" in key "Categories" in group "Desktop Entry" can be extended with another category among the following categories: Audio, or Video, or AudioVideo
==============================================================================

==================================== 2/5 =====================================
test:         validate-gschema
start time:   16:49:19
duration:     0.01s
result:       exit status 0
command:      MALLOC_PERTURB_=193 /usr/bin/glib-compile-schemas --strict --dry-run /build/kooha/src/build/data
==============================================================================

==================================== 3/5 =====================================
test:         validate-appdata
start time:   16:49:19
duration:     0.03s
result:       exit status 0
command:      MALLOC_PERTURB_=29 /usr/bin/appstream-util validate --nonet /build/kooha/src/build/data/io.github.seadve.Kooha.metainfo.xml
----------------------------------- stdout -----------------------------------
/build/kooha/src/build/data/io.github.seadve.Kooha.metainfo.xml: OK
==============================================================================

==================================== 4/5 =====================================
test:         cargo-test
start time:   16:49:19
duration:     90.49s
result:       exit status 101
command:      MALLOC_PERTURB_=45 RUST_BACKTRACE=1 PATH=/app/bin:/usr/bin:/usr/lib/sdk/llvm14/bin:/usr/lib/sdk/rust-stable/bin CARGO_HOME=/build/kooha/src/build/cargo-home /usr/bin/cargo test --manifest-path=/build/kooha/src/Kooha-2.2.2/Cargo.toml --target-dir=/build/kooha/src/build/src -- --nocapture
----------------------------------- stdout -----------------------------------

running 44 tests
test pipeline::test::odd_round_to_even ... ok
test pipeline::test::odd_round_to_even_f32 ... ok
test pipeline::test::even_round_to_even_f32 ... ok
test pipeline::test::even_round_to_even ... ok
test pipeline::test::float_round_to_even_f32 ... ok
test profile::tests::id_validity ... ok
test profile::tests::is_experimental_test ... ok
test screencast_session::handle::tests::static_variant_type ... ok
test screencast_session::handle::tests::from_variant_err ... ok
test screencast_session::handle::tests::from_variant ... ok
test screencast_session::handle_token::tests::to_variant ... ok
test recording::tests::duration ... ok
test screencast_session::handle_token::tests::uniqueness ... ok
test screencast_session::object_path::tests::static_variant_type ... ok
test screencast_session::object_path::tests::from_variant ... ok
test screencast_session::object_path::tests::to_variant ... ok
test screencast_session::tests::get_variant_ok ... ok
test screencast_session::object_path::tests::to_variant_err ... ok
test screencast_session::tests::get_variant_wrong_type ... ok
test screencast_session::types::tests::stream_static_variant_type ... ok
test screencast_session::types::tests::stream_from_variant ... ok
test screencast_session::types::tests::stream_from_variant_optional ... ok
test screencast_session::variant_dict::tests::empty ... ok
test screencast_session::variant_dict::tests::from_iter ... ok
test screencast_session::variant_dict::tests::from_variant ... ok
test screencast_session::variant_dict::tests::get_missing ... ok
test screencast_session::variant_dict::tests::get_ok ... ok
test screencast_session::variant_dict::tests::get_optional_missing ... ok
test screencast_session::variant_dict::tests::get_optional_wrong_type ... ok
test screencast_session::variant_dict::tests::get_optional_ok ... ok
test screencast_session::variant_dict::tests::get_wrong_type ... ok
test screencast_session::variant_dict::tests::static_variant_type ... ok
test screencast_session::variant_dict::tests::to_variant ... ok
test window::tests::format_time_less_than_1_hour ... ok
test window::tests::format_time_more_than_1_hour ... ok
----------------------------------- stderr -----------------------------------
   Compiling proc-macro2 v1.0.43
   Compiling unicode-ident v1.0.4
   Compiling quote v1.0.21
   Compiling syn v1.0.99
   Compiling serde_derive v1.0.144
   Compiling serde v1.0.144
   Compiling pkg-config v0.3.25
   Compiling smallvec v1.9.0
   Compiling heck v0.4.0
   Compiling version-compare v0.1.0
   Compiling autocfg v1.1.0
   Compiling libc v0.2.132
   Compiling thiserror v1.0.35
   Compiling version_check v0.9.4
   Compiling once_cell v1.14.0
   Compiling futures-core v0.3.24
   Compiling futures-task v0.3.24
   Compiling anyhow v1.0.65
   Compiling futures-util v0.3.24
   Compiling pin-project-lite v0.2.9
   Compiling pin-utils v0.1.0
   Compiling futures-channel v0.3.24
   Compiling bitflags v1.3.2
   Compiling memchr v2.5.0
   Compiling cfg-if v1.0.0
   Compiling ucd-trie v0.1.5
   Compiling gio v0.15.12
   Compiling futures-io v0.3.24
   Compiling iana-time-zone v0.1.48
   Compiling paste v1.0.9
   Compiling muldiv v1.0.0
   Compiling pretty-hex v0.3.0
   Compiling lazy_static v1.4.0
   Compiling temp-dir v0.1.11
   Compiling log v0.4.17
   Compiling cc v1.0.73
   Compiling regex-syntax v0.6.27
   Compiling weezl v0.1.7
   Compiling color_quant v1.1.0
   Compiling fragile v1.2.1
   Compiling ansi_term v0.12.1
   Compiling atomic_refcell v0.1.8
   Compiling sharded-slab v0.1.4
   Compiling cfg-expr v0.10.3
   Compiling tracing-core v0.1.29
   Compiling thread_local v1.1.4
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling gif v0.11.4
   Compiling slab v0.4.7
   Compiling num-traits v0.2.15
   Compiling num-integer v0.1.45
   Compiling num-rational v0.4.1
   Compiling memoffset v0.6.5
   Compiling libpulse-sys v1.19.3
   Compiling libpulse-mainloop-glib-sys v1.19.2
   Compiling tracing-log v0.1.3
   Compiling option-operations v0.4.1
   Compiling quick-xml v0.22.0
   Compiling aho-corasick v0.7.19
   Compiling gettext-sys v0.21.3
   Compiling tracing-subscriber v0.3.15
   Compiling chrono v0.4.22
   Compiling regex v1.6.0
   Compiling futures-executor v0.3.24
   Compiling gst-plugin-version-helper v0.7.3
   Compiling locale_config v0.3.0
   Compiling gettext-rs v0.7.0
   Compiling gst-plugin-gtk4 v0.1.1
   Compiling gst-plugin-gif v0.8.0
   Compiling thiserror-impl v1.0.35
   Compiling num-derive v0.3.3
   Compiling tracing-attributes v0.1.22
   Compiling tracing v0.1.36
   Compiling pest v2.3.1
   Compiling libpulse-binding v2.26.0
   Compiling semver-parser v0.10.2
   Compiling semver v0.11.0
   Compiling rustc_version v0.3.3
   Compiling field-offset v0.3.4
   Compiling toml v0.5.9
   Compiling quick-xml v0.25.0
   Compiling system-deps v6.0.2
   Compiling proc-macro-crate v1.2.1
   Compiling gsettings-macro v0.1.14
   Compiling glib-macros v0.15.11
   Compiling gtk4-macros v0.4.8
   Compiling glib-sys v0.15.10
   Compiling gobject-sys v0.15.10
   Compiling gio-sys v0.15.10
   Compiling cairo-sys-rs v0.15.1
   Compiling gdk-pixbuf-sys v0.15.10
   Compiling pango-sys v0.15.10
   Compiling gdk4-sys v0.4.8
   Compiling gstreamer-sys v0.18.0
   Compiling graphene-sys v0.15.10
   Compiling gstreamer-base-sys v0.18.0
   Compiling gsk4-sys v0.4.8
   Compiling gtk4-sys v0.4.8
   Compiling gstreamer-video-sys v0.18.3
   Compiling gstreamer-audio-sys v0.18.3
   Compiling gstreamer-pbutils-sys v0.18.0
   Compiling libadwaita-sys v0.2.0-alpha.2
   Compiling gdk4-x11-sys v0.4.8
   Compiling gdk4-wayland-sys v0.4.8
   Compiling glib v0.15.12
   Compiling pango v0.15.10
   Compiling cairo-rs v0.15.12
   Compiling gstreamer v0.18.8
   Compiling graphene-rs v0.15.1
   Compiling libpulse-glib-binding v2.25.1
   Compiling gstreamer-base v0.18.0
   Compiling gstreamer-pbutils v0.18.7
   Compiling gstreamer-video v0.18.7
   Compiling gdk-pixbuf v0.15.11
   Compiling gdk4 v0.4.8
   Compiling gsk4 v0.4.8
   Compiling gdk4-x11 v0.4.8
   Compiling gdk4-wayland v0.4.8
   Compiling gtk4 v0.4.8
   Compiling libadwaita v0.2.0-alpha.2
   Compiling kooha v2.2.2 (/build/kooha/src/Kooha-2.2.2)
    Finished test [unoptimized + debuginfo] target(s) in 1m 30s
     Running unittests src/main.rs (src/debug/deps/kooha-19cf5268d23cd292)
thread 'element_properties::tests::element_properties' panicked at 'GStreamer has not been initialized. Call `gst::init` first.', /build/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.8/src/structure.rs:80:9
stack backtrace:
thread 'profile::tests::incompatibles' panicked at 'GStreamer has not been initialized. Call `gst::init` first.', /build/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.8/src/structure.rs:80:9

(kooha-19cf5268d23cd292:10622): GLib-GIO-ERROR **: 16:50:49.491: Settings schema 'io.github.seadve.Kooha' is not installed
error: test failed, to rerun pass '--bin kooha'

Caused by:
  process didn't exit successfully: `/build/kooha/src/build/src/debug/deps/kooha-19cf5268d23cd292 --nocapture` (signal: 5, SIGTRAP: trace/breakpoint trap)
==============================================================================

==================================== 5/5 =====================================
test:         cargo-clippy
start time:   16:49:19
duration:     139.11s
result:       exit status 0
command:      MALLOC_PERTURB_=201 PATH=/app/bin:/usr/bin:/usr/lib/sdk/llvm14/bin:/usr/lib/sdk/rust-stable/bin CARGO_HOME=/build/kooha/src/build/cargo-home /usr/bin/cargo clippy --manifest-path=/build/kooha/src/Kooha-2.2.2/Cargo.toml --target-dir=/build/kooha/src/build/src
----------------------------------- stderr -----------------------------------
    Blocking waiting for file lock on build directory
    Checking once_cell v1.14.0
    Checking pin-project-lite v0.2.9
    Checking pin-utils v0.1.0
    Checking smallvec v1.9.0
    Checking bitflags v1.3.2
    Checking cfg-if v1.0.0
    Checking futures-io v0.3.24
    Checking muldiv v1.0.0
    Checking pretty-hex v0.3.0
    Checking lazy_static v1.4.0
    Checking regex-syntax v0.6.27
    Checking weezl v0.1.7
    Checking color_quant v1.1.0
    Checking atomic_refcell v0.1.8
    Checking ansi_term v0.12.1
    Checking fragile v1.2.1
    Checking option-operations v0.4.1
    Checking libc v0.2.132
    Checking futures-core v0.3.24
    Checking futures-task v0.3.24
    Checking memchr v2.5.0
    Checking log v0.4.17
    Checking anyhow v1.0.65
    Checking slab v0.4.7
    Checking num-traits v0.2.15
    Checking memoffset v0.6.5
    Checking gettext-sys v0.21.3
    Checking thiserror v1.0.35
    Checking sharded-slab v0.1.4
    Checking field-offset v0.3.4
    Checking futures-channel v0.3.24
    Checking tracing-core v0.1.29
    Checking thread_local v1.1.4
    Checking futures-util v0.3.24
    Checking gif v0.11.4
    Checking aho-corasick v0.7.19
    Checking tracing-log v0.1.3
    Checking tracing v0.1.36
    Checking glib-sys v0.15.10
    Checking num-integer v0.1.45
    Checking libpulse-sys v1.19.3
    Checking tracing-subscriber v0.3.15
    Checking gobject-sys v0.15.10
    Checking cairo-sys-rs v0.15.1
    Checking graphene-sys v0.15.10
    Checking gdk4-wayland-sys v0.4.8
    Checking num-rational v0.4.1
    Checking libpulse-mainloop-glib-sys v1.19.2
    Checking libpulse-binding v2.26.0
    Checking gio-sys v0.15.10
    Checking pango-sys v0.15.10
    Checking gstreamer-sys v0.18.0
    Checking gstreamer-base-sys v0.18.0
    Checking regex v1.6.0
    Checking gstreamer-video-sys v0.18.3
    Checking gstreamer-audio-sys v0.18.3
    Checking futures-executor v0.3.24
    Checking gdk-pixbuf-sys v0.15.10
    Checking glib v0.15.12
    Checking gstreamer-pbutils-sys v0.18.0
    Checking gdk4-sys v0.4.8
    Checking gsk4-sys v0.4.8
    Checking gdk4-x11-sys v0.4.8
    Checking locale_config v0.3.0
    Checking gtk4-sys v0.4.8
    Checking gettext-rs v0.7.0
    Checking libadwaita-sys v0.2.0-alpha.2
    Checking gio v0.15.12
    Checking pango v0.15.10
    Checking cairo-rs v0.15.12
    Checking gstreamer v0.18.8
    Checking graphene-rs v0.15.1
    Checking libpulse-glib-binding v2.25.1
    Checking gstreamer-base v0.18.0
    Checking gstreamer-pbutils v0.18.7
    Checking gstreamer-video v0.18.7
    Checking gst-plugin-gif v0.8.0
    Checking gdk-pixbuf v0.15.11
    Checking gdk4 v0.4.8
    Checking gsk4 v0.4.8
    Checking gdk4-wayland v0.4.8
    Checking gdk4-x11 v0.4.8
    Checking gtk4 v0.4.8
    Checking gst-plugin-gtk4 v0.1.1
    Checking libadwaita v0.2.0-alpha.2
    Checking kooha v2.2.2 (/build/kooha/src/Kooha-2.2.2)
    Finished dev [unoptimized + debuginfo] target(s) in 2m 19s
==============================================================================


Summary of Failures:

4/5 cargo-test       FAIL            90.49s   exit status 101

Ok:                 4
Expected Fail:      0
Fail:               1
Unexpected Pass:    0
Skipped:            0
Timeout:            0
```

</details>

**Comment by jirutka** [comment]
We have the same problem on Alpine Linux.

**Comment by jirutka** [comment]
There are actually more problems than that, the tests are basically broken. :(

**Comment by konstantintutsch** [comment]
This error also occurs on Gentoo Linux. I am currently writing an ebuild for Kooha in the GURU repository. 
- [Meson log](https://912990.bugs.gentoo.org/attachment.cgi?id=868672)
- [Portage log](https://912990.bugs.gentoo.org/attachment.cgi?id=868671) (Meson + system information + package manager log)
- Gentoo Bug: https://bugs.gentoo.org/912990

**Comment by SeaDve** [comment]
> thread 'profile::tests::incompatibles' panicked at 'GStreamer has not been initialized. Call `gst::init` first.', /build/kooha/src/build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gstreamer-0.18.8/src/structure.rs:80:9

This has been fixed now via https://github.com/SeaDve/Kooha/commit/abdcf5ba2447cf5a88932aa7a6db4d4aa0af92ee. Not sure why it is not caught by the CI before.

**Comment by SeaDve** [comment]
> GLib-GIO-ERROR **: 16:42:56.486: Settings schema 'io.github.seadve.Kooha' is not installed

I think this error may be harmless as the schema is first installed on the actual installation, and second, within cargo-test.
