### ISSUE TITLE
Recording doesn't save in non flatpak environment

### ISSUE THREAD

**Issue by geofflangenderfer** [SeaDve/Kooha#20]
```
$ kooha                           
audio_gst Error: gst-resource-error-quark: Could not open file "None/tmp/tmpaudio.ogg" for writing. (6) ../gstreamer/plugins/elements/gstfilesink.c(471): gst_file_sink_open_file (): /GstPipeline:pipeline0/GstFi
leSink:filesink0:
system error: Bad file descriptor
audio_gst Error: gst-core-error-quark: GStreamer error: state change f
ailed and some element failed to post a proper error message with the
reason for the failure. (4) ../gstreamer/libs/gst/base/gstbasesink.c(5
865): gst_base_sink_change_state (): /GstPipeline:pipeline0/GstFileSin
k:filesink0:
Failed to start
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/window.py", line 135, in on_stop_record
_button_clicked
    self.video_recorder.stop()
  File "/usr/share/kooha/kooha/recorders.py", line 159, in stop
    self.GNOMEScreencast.call_sync(
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesk
top.DBus.Error.NoReply: Message recipient disconnected from message bu
s without replying (4)

```

```
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.2.1
Codename:	Nibia
```

**Comment by SeaDve** [comment]
It seems like an isolated issue with arch not getting the proper tmp directory. I recommend using the flatpak version.

**Comment by SeaDve** [comment]
Just pushed the changes, you can build it from source to test it real quick.

**Comment by SeaDve** [comment]
Hi, the fix is now available in flatpak, feel free to close the issue when it is resolved.
