### ISSUE TITLE
Unable to record, no visual feedback given, only IndexError: list index out of range

### ISSUE THREAD

**Issue by meridius** [SeaDve/Kooha#38]
I'm unable to record for `kooha-1.0.4-1` on Arch. I get no visual feedback when recording fails, only the following output to terminal (when run from it).

```
Traceback (most recent call last):
  File "/usr/share/kooha/kooha/window.py", line 71, in on_start_record_button_clicked
    self.delay_timer.start(delay)
  File "/usr/share/kooha/kooha/timers.py", line 63, in start
    self.function()
  File "/usr/share/kooha/kooha/window.py", line 85, in start_recording
    self.audio_recorder = AudioRecorder(self.directory, record_audio, record_microphone)
  File "/usr/share/kooha/kooha/recorders.py", line 29, in __init__
    self.default_audio_output, self.default_audio_input = self.get_default_audio_devices()
  File "/usr/share/kooha/kooha/recorders.py", line 83, in get_default_audio_devices
    default_source = device_list[1]
IndexError: list index out of range
```

**Comment by SeaDve** [comment]
Can i get the output of `pactl info`?

**Comment by meridius** [comment]
sure, here you go

```
Nastavení serveru: /run/user/1000/pulse/native
Verze knihovního protokolu: 34
Verze serverového protokolu: 34
Je místní: ano
Index klienta: 383
Velikost dlaždice: 65472
Uživatelské jméno: lukesm01
Název hostitele: BRN-lukesm01
Název serveru: pulseaudio
Verze serveru: 14.2
Výchozí specifikace vzorku: s16le 2 ch 44100 Hz
Výchozí mapa kanálů: front-left,front-right
Výchozí cíl: alsa_output.pci-0000_00_1f.3.analog-stereo
Výchozí zdroj: alsa_input.pci-0000_00_1f.3.analog-stereo
Cookie: f497:095f
```

**Comment by SeaDve** [comment]
Ahh, was it different in different locale when you were recording? If it does, it might be because I used the keyword "Default" to find the sources, so if you are on a different locale, it will not be able to find the keyword. For temporary fix, you can either record Video only, or set your locale to English. Although, as soon as possible this day, I am going to release the fix to flathub.

**Comment by SeaDve** [comment]
Just pushed the fix to master

**Comment by meridius** [comment]
Yep, it's working with sounds when run like `LC_ALL=C kooha`. I'll use this until the fixed version is available.
However it doesn't even with sound buttons disabled when run in my locale (non-english).

Thank you for the fix.

**Comment by SeaDve** [comment]
Thanks also for reporting! Releasing it now on flathub, together with performance tweaks.

**Comment by SeaDve** [comment]
Now released in flathub : D

**Comment by SeaDve** [comment]
Any update with the issue? Thanks!

**Comment by SeaDve** [comment]
Closing due to inactivity. Please let me know if this is still a problem for you.
