### ISSUE TITLE
KDE desktop environment not supported

### ISSUE THREAD

**Issue by kaanprotryathee** [SeaDve/Kooha#60]
Im using KDE Plasma desktop environment. But this program not supports KDE desktop environment. Can the kde desktop environment be added? Please.

**Comment by SeaDve** [comment]
Currently under implementation :D

**Comment by SeaDve** [comment]
#65

**Comment by SeaDve** [comment]
Hi, would like to confirm if the latest main branch now works on KDE

**Comment by SeaDve** [comment]
there are blockers that i had, limiting the framerate kde, causes some weird things like crashing, which doesn't happen on sway nor gnome. I think it might be something in kwin

**Comment by RussH** [comment]
Hi @SeaDve it doesn't work with KDE Wayland.. Sorry not clear on getting logging from flatpak, but the CLI feedback said this

> russh@russ-surfacepro3:/var/lib/flatpak/exports/share/applications$ /usr/bin/flatpak run --branch=master --arch=x86_64 --command=kooha io.github.seadve.Kooha
> 
> (python3:2): Gtk-CRITICAL **: 16:41:43.006: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
> 
> (python3:2): Gtk-CRITICAL **: 16:41:43.006: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed
> Traceback (most recent call last):
>   File "/app/share/kooha/kooha/main.py", line 37, in do_startup
>     Gtk.StyleContext.add_provider_for_display(
> TypeError: Argument 0 does not allow None as a value
> Traceback (most recent call last):
>   File "/app/share/kooha/kooha/main.py", line 49, in do_activate
>     window = Window(self.settings, application=self)
> AttributeError: 'Application' object has no attribute 'settings'
>  

I'll check with kwin in a bit..

**Comment by RussH** [comment]
> likely because it is run from cli, because based from the error, the display is none

when I tried to click on the icon, it just didn't launch unfortunately. I'm on KDE Neon which I know is problematic sometimes - so possibly you need a 'standard' KDE distro to test with

**Comment by RussH** [comment]
..and on kwin/X11 it does launch from the icon - but when clicking on record I get an error pop-up 'Failed to create session' and it goes no further.

**Comment by SeaDve** [comment]
i checked on kde x11 and for some reason it doesn't have a dbus interface for screencast

**Comment by witem** [comment]
Hi @SeaDve 
I try to use the last `main` on KDE with Wayland, but receiving an error: 
```
(python3:140944): Gtk-CRITICAL **: 17:27:12.836: Error building template class 'Window' for an instance of type 'Window': .:0:0 Invalid object type 'AdwViewStack'
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 169, in <lambda>
    lambda s: init_template(s, cls, base_init_template)
  File "/usr/lib/python3.9/site-packages/gi/_gtktemplate.py", line 192, in init_template
    raise RuntimeError(
RuntimeError: Handler '_get_audio_toggles_enablement' was declared with @Gtk.Template.Callback but was not present in template
```
Thanks!

**Comment by SeaDve** [comment]
you will need the latest version of libadwaita or you can replace every AdwViewStack with GtkStack in data/window.ui

**Comment by witem** [comment]
I use `libadwaita` - `1.0.0alpha.1-1` seems it almost the last build. Based on: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/main/meson.build#L2

**Comment by SeaDve** [comment]
you'll need the latest commit not latest release

**Comment by witem** [comment]
Change `AdwViewStack` with `GtkStack` in `data/ui/window.ui` helped.
But when I try to start recording, after selecting source(window or monitor) I receive error: `(python3:381003): io.github.seadve.Kooha-WARNING **: 10:47:59.513: (recorder.py, _build_pipeline, 97) gst_parse_error: no element "pipewiresrc" (1)`

**Comment by SeaDve** [comment]
you'll need pipewire plugin for gstreamer, im not sure the name of package for your distro

**Comment by witem** [comment]
yeah, after installing `gst-plugin-pipewire` I can start record in UI, but after starting I can't stop it. Only by closing or killing `kooha`.
Logs in the console:
```
ython3:407712): GLib-GIO-DEBUG: 11:14:57.859: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(python3:407712): dconf-DEBUG: 11:14:57.895: watch_fast: "/io/github/seadve/Kooha/" (establishing: 0, active: 0)
(python3:407712): dconf-DEBUG: 11:14:57.895: watch_established: "/io/github/seadve/Kooha/" (establishing: 1)
(python3:407712): dconf-DEBUG: 11:14:57.899: watch_fast: "/io/github/seadve/Kooha/" (establishing: 0, active: 1)
(python3:407712): io.github.seadve.Kooha-DEBUG: 11:15:00.404: (recorder.py, ready, 128) is_show_pointer: False
(python3:407712): io.github.seadve.Kooha-DEBUG: 11:15:00.405: (recorder.py, ready, 129) is_selection_mode: False
io.github.seadve.Kooha-INFO: 11:15:00.406: Session created
io.github.seadve.Kooha-INFO: 11:15:00.413: Sources selected
```
UI after record clicked and source selected: ![kooha](https://user-images.githubusercontent.com/1782530/125916101-d8409860-01ff-4f92-a800-32573fc578fc.png)

**Comment by SeaDve** [comment]
Sorry! I missed the notification. @witem 
I think that issue may be coming from kwin. I notice that limiting the framerate, makes gst-pipewire crash, which doesn't happen on sway nor gnome. I'm still investigating on the issue, but I can reproduce it on my kde device.

**Comment by possessedbysatan** [comment]
Here's my 2 cents (KDE 5.22.90-1 on xorg).
This happens when I click start recording:

```
DEBUG=1 kooha 

(kooha:64422): Adwaita-WARNING **: 18:56:07.797: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
 ERROR kooha::backend::screencast_portal > Error from screencast call: Response(Other)
```

**Comment by buresu** [comment]
Hi,
I have the same problem.
When I start recording, I get the following error.
```
(kooha:93582): Gdk-WARNING **: 21:52:20.316: Server is missing xdg_foreign support
```

I think this problem is caused by a mismatch in the xdg_foreign version.
The xdg_foreign version in kwayland is v2 and the one in gtk is v1.

I found the corresponding MR, but it doesn't seem to be merged.
https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1395

**Comment by ilya-fedin** [comment]
> (kooha:93582): Gdk-WARNING **: 21:52:20.316: Server is missing xdg_foreign support

I have such a error as well. The problem seem to be somewhere at https://github.com/SeaDve/Kooha/blob/654f8dad17e7703abfbf3b95aaa398c3706bc68e/src/backend/screencast_portal.rs#L77 and feels like some kind of exception as the further code doesn't seem to be executed while the error is not critical by its nature.

**Comment by ilya-fedin** [comment]
I reported the deadlock to ashpd: https://github.com/bilelmoussaoui/ashpd/issues/83

**Comment by SeaDve** [comment]
FWIW, I dropped the dependency on ashpd for better error messages and more control.

**Comment by Snaggly** [comment]
I got to record something on KDE however the timings are completely off. It records at least twice the speed upon and refresh and doesn't record anything (timer stays frozen) when the selected area stays stationary. The resulted video is then ofc being played back in slow motion, see attachment.

https://user-images.githubusercontent.com/1353354/186767018-b235c946-b8a9-4d36-9edb-c8ff2bbaadec.mp4

**Comment by SeaDve** [comment]
> I got to record something on KDE however the timings are completely off. It records at least twice the speed upon and refresh and doesn't record anything (timer stays frozen) when the selected area stays stationary. The resulted video is then ofc being played back in slow motion, see attachment.
> Kooha-2022-08-25-22-53-09.mp4

Was that 2.1.1 or built from main branch?

**Comment by Snaggly** [comment]
@SeaDve This was from the latest version available on Flathub. 2.1.1 I believe it is.

**Comment by SeaDve** [comment]
Closing this since KDE already has working ScreenCast portal, otherwise, please open another issue, thanks!
