### ISSUE TITLE
Application doesn't start: AttributeError: 'Application' object has no attribute 'settings'

### ISSUE THREAD

**Issue by scrool** [SeaDve/Kooha#99]
I have installed application from Flathub:
```
$ flatpak install flathub io.github.seadve.Kooha
Looking for matches…

io.github.seadve.Kooha permissions:
    ipc        fallback-x11        pulseaudio            wayland
    x11        dri                 file access [1]       dbus access [2]

    [1] xdg-videos
    [2] org.gnome.Shell.Screencast, org.gnome.Shell.Screenshot


        ID                            Branch Op Remote  Download
 1. [✓] io.github.seadve.Kooha.Locale stable i  flathub   3.6 kB / 103.8 kB
 2. [✓] io.github.seadve.Kooha        stable i  flathub 395.2 kB / 411.2 kB
Installation complete.
$ flatpak list | grep Kooha
Kooha	io.github.seadve.Kooha	1.2.1	stable	system
```

and on run:
```
$ flatpak run io.github.seadve.Kooha

(io.github.seadve.Kooha:2): Gtk-CRITICAL **: 18:07:13.872: gtk_icon_theme_get_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(io.github.seadve.Kooha:2): Gtk-CRITICAL **: 18:07:13.872: gtk_icon_theme_add_resource_path: assertion 'GTK_IS_ICON_THEME (self)' failed
Traceback (most recent call last):
  File "/app/share/kooha/kooha/main.py", line 45, in do_startup
    Gtk.StyleContext.add_provider_for_display(
TypeError: Argument 0 does not allow None as a value
Traceback (most recent call last):
  File "/app/share/kooha/kooha/main.py", line 57, in do_activate
    self.window = KoohaWindow(self.settings, application=self)
AttributeError: 'Application' object has no attribute 'settings'
$
```

I'm running Fedora 34 Workstation, Gnome 40 on Wayland.

**Comment by scrool** [comment]
Additionaly going through https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist

2. Is the PipeWire service running?

```
$ systemctl --user status pipewire.socket pipewire
● pipewire.socket - Multimedia System
     Loaded: loaded (/usr/lib/systemd/user/pipewire.socket; enabled; vendor pr>
     Active: active (running) since Thu 2021-08-19 18:04:52 CEST; 12min ago
...

● pipewire.service - Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; disabled; vendor >
    Drop-In: /usr/lib/systemd/user/pipewire.service.d
             └─00-uresourced.conf
     Active: active (running) since Thu 2021-08-19 18:04:54 CEST; 12min ago
...
```

3. Is the Pipewire Multimedia Session Manager service running?

No, it doesn't seem to exist as a separate service on Fedora:
```
$ systemctl --user status pipewire-media                
Unit pipewire-media.service could not be found.
$ rpm -qf /usr/bin/pipewire-media-session
pipewire-0.3.33-3.fc34.x86_64
$ rpm -ql pipewire | grep service
/usr/lib/systemd/user/pipewire.service
```

4. Is the xdp service running?
```
$ systemctl --user status xdg-desktop-portal
● xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Thu 2021-08-19 18:05:34 CEST; 24min ago
...
```

5. Does the xdp service know your wayland socket?
```
$ env | grep '^WAYLAND_DISPLAY='
WAYLAND_DISPLAY=wayland-0
```

6. Does the xdp service know what your compositor is?
```
$ < "/proc/$(pidof xdg-desktop-portal)/environ" tr '\0' '\n' | grep '^XDG_CURRENT_DESKTOP='
XDG_CURRENT_DESKTOP=GNOME
```

**Comment by SeaDve** [comment]
Hello there, thanks for detailed info

**Comment by SeaDve** [comment]
The "It doesn't work page" mostly applies on the latest (as in main branch). The error seems weird as it has nothing to do with pipewire etc. It seems to not detect your display

**Comment by SeaDve** [comment]
You can install via here too https://github.com/SeaDve/Kooha/suites/3542023437/artifacts/84804409, so you don't have to build a gazillion of packages just to test it

**Comment by SeaDve** [comment]
Additionally, the "Application does not have attribute settings" is a false positive, it is a python thing where it doesn't terminate the program, even it got a critical error, giving a irrelevant error message.

**Comment by scrool** [comment]
> You can install via here too https://github.com/SeaDve/Kooha/suites/3542023437/artifacts/84804409, so you don't have to build a gazillion of packages just to test it

Thanks for that one. I have installed it and ran:
```
$ flatpak install kooha-devel.flatpak

io.github.seadve.Kooha.Devel permissions:
    fallback-x11     pulseaudio    wayland    x11    dri    file access [1]    dbus access [2]

    [1] xdg-videos
    [2] org.a11y.Bus, org.gnome.Shell


        ID                                      Branch           Op           Remote                 Download
 1. [✓] io.github.seadve.Kooha.Devel            master           i            devel-origin           0 bytes

Installation complete.
$ flatpak run io.github.seadve.Kooha.Devel
0:00:00.027452509     3 0x5603b5b326d0 WARN                 default gstvaapipluginutil.c:974:gst_vaapi_driver_is_whitelisted: Unsupported VA driver: Intel iHD driver for Intel(R) Gen Graphics - 21.1.3 (). Export environment variable GST_VAAPI_ALL_DRIVERS to bypass
0:00:00.053474186     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x120000: 'AVR (Audio Visual Research)' is not mapped
0:00:00.053519473     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x180000: 'CAF (Apple Core Audio File)' is not mapped
0:00:00.053529682     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x100000: 'HTK (HMM Tool Kit)' is not mapped
0:00:00.053540180     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xc0000: 'MAT4 (GNU Octave 2.0 / Matlab 4.2)' is not mapped
0:00:00.053546481     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xd0000: 'MAT5 (GNU Octave 2.1 / Matlab 5.0)' is not mapped
0:00:00.053553386     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x210000: 'MPC (Akai MPC 2k)' is not mapped
0:00:00.053560454     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0xe0000: 'PVF (Portable Voice Format)' is not mapped
0:00:00.053574692     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x160000: 'SD2 (Sound Designer II)' is not mapped
0:00:00.053584747     3 0x5603b5b326d0 WARN                 default gstsf.c:97:gst_sf_create_audio_template_caps: format 0x190000: 'WVE (Psion Series 3)' is not mapped
[I][000075990.800318][pipewire.c:462 pw_init()] version 0.3.25
thread 'main' panicked at 'Unable to start GTK4.: BoolError { message: "Failed to initialize GTK", filename: "/run/build/kooha/_flatpak_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk4-0.2.0/src/rt.rs", function: "gtk4::rt", line: 111 }', src/main.rs:38:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

and interestingly followup attempts to run displayed only last part of warnings/errors:
```
$ flatpak run io.github.seadve.Kooha.Devel
thread 'main' panicked at 'Unable to start GTK4.: BoolError { message: "Failed to initialize GTK", filename: "/run/build/kooha/_flatpak_build/cargo-home/registry/src/github.com-1ecc6299db9ec823/gtk4-0.2.0/src/rt.rs", function: "gtk4::rt", line: 111 }', src/main.rs:38:17
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by SeaDve** [comment]
The issue seems to be coming from the same source for both versions. I'm not sure why. Does other flatpak gtk4 apps works too?

**Comment by scrool** [comment]
You were right - I tried other gtk4 app and it didn't start either. So I have removed and installed gnome-desktop group and after a reboot Kooha starts.
